### ISSUE TITLE
Interventions tab: Error : Assigned data `list(x ...` must be compatible with existing data

### ISSUE THREAD

**Issue by Sjors** [BDI-pathogens/covid-19_shiny#1]
I'm using RStudio 1.2.5033 (R version 3.6.3) on macOS 10.15.4, installed via Homebrew. I opened `global.R`, installed the packages it needed and then ran the app.

The first tab Infectiousness shows up and the charts look the same as on the website.

However the second tab doesn't contain a chart, and there's an error in the log:

```
Listening on http://127.0.0.1:5940
Error : 
Error : 
Error : 
Error : 
Error : 
Error : Assigned data `list(x = rownames(m)[[i]], x = colnames(m)[[j]], z = m[i, j])` must be compatible with existing data.
ℹ Error occurred for column `x`.
x No common type for `value` <character> and `x` <double>.
```

I think it refers to these lines:

https://github.com/BDI-pathogens/covid-19_shiny/blob/e795b8849b3c6d88b8ad1b0776c20ff14890f71d/server.R#L1096-L1105

Unfortunately I'm new to R so I have no suggestion on what to fix here. Or maybe I'm doing something wrong.

**Comment by MichelleKendall** [comment]
Hi,

I think there are two things happening here. The empty "error" messages are simply to do with reactive expressions awaiting their input values on startup. These are caught and handled by the "validate, need" expressions and are nothing to worry about.

The error "Assigned data..." looks like a package management issue, probably to do with tidyverse. I recommend making sure that your R installation and all your packages are up to date and then trying again - let me know if it persists.

Thanks,

Michelle

**Comment by Sjors** [comment]
Hey @MichelleKendall, it was a fresh installation, but "Check for package updates..." did install some updates. I restarted Rstudio, and tried again, but no luck.

<img width="837" alt="Schermafbeelding 2020-04-03 om 14 33 54" src="https://user-images.githubusercontent.com/10217/78361197-4dec8580-75b8-11ea-9fe8-90b736e26c60.png">

**Comment by MichelleKendall** [comment]
Excellent, thanks for sharing all this. It turns out I was still on R version 3.6.2 and got the same error as you when I updated. It was a "character" versus "numeric" handling error which I believe I've now fixed. Please could I ask you to let me know whether the problem persists after commit ee20f8f ? Thanks.

**Comment by Sjors** [comment]
That worked, thanks!

By the way, it might be useful to mention in the README that `global.R` is the file to open (I initially tried `server.R`, which didn't auto-fetch the dependencies).

**Comment by MichelleKendall** [comment]
Great! Will do, thanks.
