### ISSUE TITLE
Relative infectiousness of PRE-symptomatic compared with symptomatic individuals

### ISSUE THREAD

**Issue by Kafiland** [BDI-pathogens/covid-19_shiny#2]
I read your very interesting study,
However I'd like to be able to play with an additional parameter that would be: Relative infectiousness of **pre-**symptomatic compared with symptomatic individuals. In a first way it could be a parameter xp such as xa for asymptomatic. But even better would be a function xp(τ)

for example   (1−Pa)(1−s(τ))xp(τ)βs(τ)+(1−Pa)s(τ)βs(τ)

Thanks again for your amazing work, stay safe.

**Comment by ChrisHIV** [comment]
Hi there, xp as a constant (not a function of tau) can be changed in the source code underpinning the shiny app, available here: https://doi.org/10.5281/zenodo.3727255 in Theta_EstimatedByRenewalEquation.R, line 74. If you follow xp all the way through the code (including where the meat of the maths happens, in Theta_EstimatedByRenewalEquation_funcs.R) you might be able to make it a function of tau. Sorry not to be able to offer more help than that.
